/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "qkzclkymgvgyisltruuu"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFremNsa3ltZ3ZneWlzbHRydXV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE1NzYxMzAsImV4cCI6MjA3NzE1MjEzMH0.mqVjigdjVquPSzRxR5ISMg--Hqrxr317ChhmcFO0-_M"